#!/bin/sh

# Author: Lilan Manoj
# Date: 2020-10-26
# Description: Create apache virtual host
# Script follows here:

PROJECT_ROOT_DIR=""
DOMAIN_NAME=""
SITES_AVAIL_DEFAULT_DIR="/etc/apache2/sites-available/"
HOSTS_FILE="/etc/hosts"

read -p "Enter apache document root [/var/www/html]: " APACHE_DOCUMENT_ROOT
APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT:-/var/www/html}

until [ $DOMAIN_NAME ]
do
    echo "Enter virtual domain name (without www):"
    read DOMAIN_NAME
done

until [ $PROJECT_ROOT_DIR ]
do
    echo "Enter project document root (public directory):"
    read PROJECT_ROOT_DIR
done

if [ ! -e $PROJECT_ROOT_DIR ]
then
    sudo mkdir $PROJECT_ROOT_DIR
    echo $PROJECT_ROOT_DIR"/"$DOMAIN_NAME".conf directory created - Done"
else
    echo $PROJECT_ROOT_DIR"/"$DOMAIN_NAME".conf directory exist - Done"
fi

PROJECT_DOCUMENT_ROOT=$APACHE_DOCUMENT_ROOT"/"$DOMAIN_NAME
sudo ln -s $PROJECT_ROOT_DIR $PROJECT_DOCUMENT_ROOT

cd $PROJECT_DOCUMENT_ROOT

VIRTUALHOST_CONF_FILE=$DOMAIN_NAME".conf"

echo "# This virtual host configuration file" > $VIRTUALHOST_CONF_FILE
echo "# was autogenerated by virtualizer" >> $VIRTUALHOST_CONF_FILE
echo "# by Lilan Manoj" >> $VIRTUALHOST_CONF_FILE
echo "<VirtualHost *:80>" >> $VIRTUALHOST_CONF_FILE
echo "\tServerAdmin admin@$DOMAIN_NAME" >> $VIRTUALHOST_CONF_FILE
echo "\tServerName $DOMAIN_NAME" >> $VIRTUALHOST_CONF_FILE
echo "\tServerAlias www.$DOMAIN_NAME" >> $VIRTUALHOST_CONF_FILE
echo "\tDocumentRoot $PROJECT_DOCUMENT_ROOT" >> $VIRTUALHOST_CONF_FILE
echo "\tErrorLog ${APACHE_LOG_DIR}/error.log" >> $VIRTUALHOST_CONF_FILE
echo "\tCustomLog ${APACHE_LOG_DIR}/access.log combined" >> $VIRTUALHOST_CONF_FILE
echo "</VirtualHost>" >> $VIRTUALHOST_CONF_FILE

echo "\r\n"
echo "Created $VIRTUALHOST_CONF_FILE with host configurations - Done"

if [ -e $SITES_AVAIL_DEFAULT_DIR ]
then
    sudo mv "./"$VIRTUALHOST_CONF_FILE $SITES_AVAIL_DEFAULT_DIR
    echo "Moved $VIRTUALHOST_CONF_FILE to $SITES_AVAIL_DEFAULT_DIR - Done"
else
    echo "Error: sites-available directory not found in ($SITES_AVAIL_DEFAULT_DIR)"
    echo "Moved $VIRTUALHOST_CONF_FILE to $SITES_AVAIL_DEFAULT_DIR - Failed!"
    return 1
fi

echo "\r\n"
echo "Enabling $VIRTUALHOST_CONF_FILE ..."
a2ensite $VIRTUALHOST_CONF_FILE

echo "\r\n"
echo "Restarting apache2 ..."
sudo systemctl restart apache2

echo "\r\n"
echo "Adding hosts file entries for $DOMAIN_NAME in $HOSTS_FILE ..."
echo "# Host entry for $DOMAIN_NAME added by virtualizer" >> $HOSTS_FILE
echo "127.0.0.1 $DOMAIN_NAME" >> $HOSTS_FILE
echo "Added hosts file entries for $DOMAIN_NAME in $HOSTS_FILE - Done"

echo "\r\n"
echo "run `systemctl status apache2` to verify apache status"
echo "Process finished!"
